Implement kv cache (#74)
* Allow parsing parameters from a config file (#141)

* Allow parsing parameters from a config file

* Address nits

* Support for beam search and kv_cache

* Added tiny test + black

* separate tiny generate test from generate test

* set dataset version to avoid error: AttributeError: module 'threading' has no attribute '_Condition'.

* compatible datasets version and unified python versions to 3.10

* Using xformers LowerTriangularFromBottomRightMask instead of custom mask

* revert back to using custom mask because it is not compatible with the xformers version that we need

* added tiny beam generation test and fixed cache reorder (thanks Rui)

---------

Co-authored-by: Achal Dave <achalddave@gmail.com>